name: Opamp spice testbench

on:
    push:
        branches:
            - main
    pull_request:
        paths:
            - 'openfasoc/common/**'
            - 'openfasoc/generators/common/**'
            - 'openfasoc/generators/glayout/**'
    workflow_dispatch:

jobs:
    glayout_sky130:
        runs-on: ubuntu-latest
        steps:
            - name: Remove unnecessary files
              run: |
                du . -h
                sudo rm -rf /usr/share/dotnet
                sudo rm -rf "$AGENT_TOOLSDIRECTORY"
                du . -h

            - name: Checkout repo
              uses: actions/checkout@v4
            
            - name: Opamp Parametric sims
              env:
                  IMAGE_NAME: msaligane/openfasoc:stable
              run: |
                  cd $GITHUB_WORKSPACE
                  touch glayout.log
                  docker run --rm \
                      -v $PWD:$PWD \
                      -w $PWD \
                      $IMAGE_NAME \
                      bash -c "\
                      cp ./.github/scripts/test_glayout_ci.py ./openfasoc/generators/glayout/tapeout/tapeout_and_RL/. &&\
                      pip uninstall glayout -y &&\
                      pip3 install -r ./openfasoc/generators/glayout/requirements.txt &&\
                      cd ./openfasoc/generators/glayout/tapeout/tapeout_and_RL/ &&\
                      pip3 install prettyprint prettyprinttree gdstk &&\
                      pip3 install -r requirements.txt
                      python3 test_glayout_ci.py --component opamp_parametric
                      " && exit_code=$? | tee -a glayout.log
                  if [ $? -ne 0 ]; then exit 1; fi
                  if grep "\[ERROR\]" glayout.log; then exit 1; else exit 0; fi