name: Tempsense_run

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  sky130hd_temp:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: Fix self-host Permissions
        run:
          sudo chmod -R a+rwx /actions-runner/

      - name: Checkout repo
        uses: actions/checkout@v2
        # with:
        #   ref: topic/GCP

      # - name: Clone OpenLane repo
      #   run: |
      #     cd /github
      #     git clone https://github.com/The-OpenROAD-Project/OpenLane.git

      # - name: Make OpenLane Image
      #   run: |
      #     cd /tmp/OpenLane/docker
      #     make merge

      # Build openlane:current instead of merging
      # `make openlane` applies the current tag to the image

      # - name: Make OpenLane image
      #   run: |
      #     cd /github/OpenLane
      #     make openlane

      # - name: Build PDK
      #   env:
      #     PDK_ROOT: /github/OpenLane/pdks
      #     IMAGE_NAME: efabless/openlane:2021.12.22_01.51.18
      #   run: |
      #     cd /github/OpenLane
      #     make pdk

      - name: Make Sky130HD Temp
        env:
          PDK_ROOT: /github/OpenLane/pdks
          IMAGE_NAME: efabless/openlane:2021.12.22_01.51.18
        run: |
          cd $GITHUB_WORKSPACE
          docker run --rm\
            -e GITHUB_ACTIONS=1\
            -v /github/OpenLane:/OpenLane\
            -v $PDK_ROOT:$PDK_ROOT\
            -e PDK_ROOT=$PDK_ROOT\
            -v $PWD:$PWD\
            -w $PWD\
            $IMAGE_NAME\
            bash -c "\
              yum install -y time &&\
              cd ./generators/temp-sense-gen &&\
              make sky130hd_temp\
            "
