name: TEST

on:

    push:
    
    pull_request:

jobs:
  test_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install numpy matplotlib pandas XlsxWriter pyyaml pyinstaller jinja2

      - name: Install Magic
        run:  |
          cd /home/runner/work
          sudo apt-get install m4
          sudo apt-get install tcsh
          sudo apt-get install csh
          sudo apt-get install libx11-dev
          sudo apt-get install tcl-dev tk-dev
          git clone https://github.com/RTimothyEdwards/magic.git
          cd magic
          ./configure
          make
          sudo make install
      
      - name: Install Netgen
        run:  |
          cd /home/runner/work
          git clone https://github.com/RTimothyEdwards/netgen.git
          cd netgen
          ./configure
          make
          sudo make install
      
      - name: Install OpenLane
        run: |
          cd /home/runner/work
          export PDK_ROOT=/home/runner/work/
          git clone https://github.com/The-OpenROAD-Project/OpenLane.git
          cd OpenLane/
          make

      - name: Check Paths
        run: |
          echo "/home/runner/work: "
          cd /home/runner/work
          ls
          echo "/home/runner/work/open_pdks: "
          cd /home/runner/work/open_pdks
          ls
          echo "/home/runner/work/open_pdks/sky130/sky130A: "
          cd /home/runner/work/open_pdks/sky130/sky130A
          ls
 
      # - name: Install OpenROAD
      #   run:  |
      #     cd /home/runner/work
      #     git clone --recursive https://github.com/The-OpenROAD-Project/OpenROAD.git
      #     cd OpenROAD
      #     sudo ./etc/DependencyInstaller.sh -dev
      #     sudo ./etc/Build.sh
 
      # - name: PDK installation
      #   run: cd ${GITHUB_WORKSPACE}/ && make pdk
 
      # - name: Install Klayout
      #   run:  |
      #     cd /home/runner/work
      #     git clone https://github.com/KLayout/klayout.git
      #     cd klayout
      #     sudo apt-add-repository ppa:rock-core/qt4
      #     sudo apt-add-repository ppa:ubuntu-toolchain-r/test
      #     sudo apt update
      #     sudo apt install qt4-default
      #     sudo apt-get install gcc-4.7
      #     sudo apt-get install build-essential
      #     ./build.sh -option '-j8' -noruby -without-qt-multimedia -without-qt-xml -without-qt-svg
 
      # - name: Install PDK
      #   run:  |
      #     cd /home/runner/work
      #     git clone https://github.com/RTimothyEdwards/open_pdks.git
      #     cd open_pdks
      #     ./configure --enable-sky130-pdk
      #     make
      #     sudo make install
          
      # docker run -v $(pwd):/mnt -w /mnt efabless/openlane sh -c 'make sky130hd_temp'
      
      - name: Locate gen-design folder
        run:  |
          cd /home/runner/work/OpenFASOC/OpenFASOC/generators/temp-sense-gen
          make sky130hd_temp


